routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// dashboard
Route::group(['prefix' => 'dashboards'], function () {
    Route::get('/environment-monitor', "dashboardController@environmentMonitor")->name('dashboards.environmentMonitor');
    Route::get('/environment-monitor-b2', "dashboardController@environmentMonitorB2")->name('dashboards.environmentMonitorB2');
    Route::get('/inventory', "dashboardController@inventory")->name('dashboards.inventory');
    Route::get('/inventory-b2', "dashboardController@inventoryB2")->name('dashboards.inventoryB2');
    Route::get('/infra', "dashboardController@infra")->name('dashboards.infra');
    Route::get('/infra-b2', "dashboardController@infraB2")->name('dashboards.infraB2');
});
Route::resource('dashboards', "dashboardController");

//manual auto
Route::group(['prefix' => 'controls'], function () {
    Route::get('/broiler-temperature', "manualAutoController@broilerTemperature")->name('controls.broilerTemperature');
    Route::get('/ventilation-system', "manualAutoController@ventilationSystem")->name('controls.ventilationSystem');
    Route::get('/light-dimmer', "manualAutoController@lightDimmer")->name('controls.lightDimmer');
    Route::get('/auto-feeder-system', "manualAutoController@autoFeederSystem")->name('controls.autoFeederSystem');
    Route::get('/water-dosing-system', "manualAutoController@waterDosing")->name('controls.waterDosing');
    Route::get('/heater', "manualAutoController@heater")->name('controls.heater');
    Route::get('/static-pressure', "manualAutoController@staticPressure")->name('controls.staticPressure');
    Route::get('/tunnel-curtain', "manualAutoController@tunnelCurtain")->name('controls.tunnelCurtain');

});
Route::resource('controls', "manualAutoController");

//inventory
Route::group(['prefix' => 'inventories'], function () {
    Route::get('/doc', "inventoryController@doc")->name('inventories.doc');
    Route::get('/feed', "inventoryController@feed")->name('inventories.feed');
    Route::get('/supplements', "inventoryController@supplements")->name('inventories.supplements');
    Route::get('/cleaning-chemicals', "inventoryController@cleaningChemicals")->name('inventories.cleaningChemicals');

});
Route::resource('inventories', "inventoryController");

//addons
Route::group(['prefix' => 'addOns'], function () {
    Route::get('/chart', "addOnController@chart")->name('addOns.chart');
    Route::get('/cycle-record', "addOnController@cycleRecord")->name('addOns.cycleRecord');

});
Route::resource('addOns', "addOnController");

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/footer.blade.php
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; MyDGtech By Boson 2022</p></div>
</footer>

resources/views/header.blade.php
<!-- header -->
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
     <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <a class="navbar-brand ps-3" href="index.html">Digital Farm Management</a>
    <!-- Sidebar Toggle-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
        </div>
    </form>
    
    <!-- Navbar right corner of the age contains settings  , activity logs , logout -->

    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <!--
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>-->
                <li><a class="dropdown-item" href="login.html">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/side-bar.blade.php
<!-- sidebar -->
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{ route('dashboards.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    System Overview
                </a>
                <!-- dashboard lists -->
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseDashboards" aria-expanded="false" aria-controls="collapseDashboards">
                    <div class="sb-nav-link-icon"><i class="far fa-list-alt"></i></div>
                    Dashboard Lists
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseDashboards" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSubDashboards" aria-expanded="false" aria-controls="collapseDashboards">
                            <div class="sb-nav-link-icon"></div>
                            Environment Monitoring
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseSubDashboards" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{ route('dashboards.environmentMonitor') }}">Boiler 1</a>
                                <a class="nav-link" href="{{ route('dashboards.environmentMonitorB2') }}">Boiler 2</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSubDashboards2" aria-expanded="false" aria-controls="collapseDashboards">
                            <div class="sb-nav-link-icon"></div>
                            Inventory
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseSubDashboards2" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{ route('dashboards.inventory') }}">Boiler 1</a>
                                <a class="nav-link" href="{{ route('dashboards.inventoryB2') }}">Boiler 2</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseSubDashboards3" aria-expanded="false" aria-controls="collapseDashboards">
                            <div class="sb-nav-link-icon"></div>
                            Infra
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseSubDashboards3" >
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{ route('dashboards.infra') }}">Boiler 1</a>
                                <a class="nav-link" href="{{ route('dashboards.infraB2') }}">Boiler 2</a>
                            </nav>
                        </div>
                    </nav>
                </div>

                <!--Control setting section -->
                <div class="sb-sidenav-menu-heading">Operation</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseControls" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Manual & Auto Controls
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseControls" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route('controls.broilerTemperature') }}">Broiler Temperature</a>
                        <a class="nav-link" href="{{ route('controls.ventilationSystem') }}">Ventilation System</a>
                        <a class="nav-link" href="{{ route('controls.lightDimmer') }}">Light Dimmer</a>
                        <a class="nav-link" href="{{ route('controls.autoFeederSystem') }}">Automatic Feeder</a>
                        <a class="nav-link" href="{{ route('controls.waterDosing') }}">Water Dosing</a>
                        <a class="nav-link" href="{{ route('controls.heater') }}">Heaters</a>
                        <a class="nav-link" href="{{ route('controls.staticPressure') }}">Static Pressure</a>
                        <a class="nav-link" href="{{ route('controls.tunnelCurtain') }}">Tunnel Curtains</a>
                    </nav>
                </div>
                <!--Management-->
                <div class="sb-sidenav-menu-heading">Management</div>
                <!--Inventory-->
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts1" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Inventory
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts1" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ route('inventories.doc') }}">DOC</a>
                        <a class="nav-link" href="{{ route('inventories.feed') }}">Feed</a>
                        <a class="nav-link" href="{{ route('inventories.supplements') }}">Suppliments</a>
                        <a class="nav-link" href="{{ route('inventories.cleaningChemicals') }}">Cleaning chemicals</a>
                    </nav>
                </div>
                <!--Weight-->
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages1" aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Weights and FOC
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages1" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Cycle Record
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                            Sloter house
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <!--Addons-->
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="{{ route('addOns.chart') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Charts
                </a>
                <a class="nav-link" href="{{ route('addOns.cycleRecord') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Cycle Records
                </a>
            </div>
        </div>
        <!--Login info-->
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            MyDGtech Developer
        </div>
    </nav>
</div>